CREATE TABLE FORNECEDOR(
COD_FORNECEDOR INT NOT NULL auto_increment,
NOME_EMPRESA_FORNECEDOR VARCHAR (240) NOT NULL,
primary key (COD_FORNECEDOR));

 CREATE TABLE AGENDA (
 COD_AGENDA INT NOT NULL auto_increment,
 HORARIO_AGENDA TIME NOT NULL,
 DATA_AGENDA DATE NOT NULL,
 SERVICO_AGENDA  VARCHAR (120) NOT NULL,
 primary key (COD_AGENDA));

CREATE TABLE FUNCIONARIO(
COD_FUNCIONARIO INT NOT NULL auto_increment,
STATUS_FUNCIONARIO tinyint NOT NULL,
AGENDA_COD_AGENDA INT NOT NULL,
primary key (COD_FUNCIONARIO),
FOREIGN KEY (AGENDA_COD_AGENDA) REFERENCES AGENDA(COD_AGENDA));

CREATE TABLE PESSOA(
COD_PESSOA INT NOT NULL auto_increment,
NOME_PESSOA VARCHAR(40) NOT NULL,
CPF_CNPJ_PESSOA INT NOT NULL,
CONTATO_PESSOA VARCHAR(240) NOT NULL,
EMAIL_PESSOA VARCHAR (240) NOT NULL,
TIPO_PESSOA  INT (1) NOT NULL,
FORNECEDOR_COD_FORNECEDOR INT NOT NULL,
FUNCIONARIO_COD_FUNCIONARIO INT NOT NULL,
primary key (COD_PESSOA),
FOREIGN  KEY(FORNECEDOR_COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR),
foreign key (FUNCIONARIO_COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
);

CREATE TABLE ANIMAL(
COD_ANIMAL INT NOT NULL auto_increment,
 NOME_ANIMAL VARCHAR(120) NOT NULL,
RACA_ANIMAL VARCHAR (240) NOT NULL,
ESPECIE_ANIMAL VARCHAR(240) NOT NULL,
IDADE_ANIMAL INT(3) NOT NULL,
VACINA_DIA_ANIMAL tinyint NOT NULL,
primary key (COD_ANIMAL));
 


 CREATE TABLE PRODUTO(
 COD_PRODUTO INT NOT NULL auto_increment,
 DESCRICAO_PRODUTO VARCHAR (120) NOT NULL,
 PRECO_VENDA DECIMAL(6,2) NOT NULL,
 PRECO_COMPRA decimal(6,2) NOT NULL,
 BANHO_COD_BANHO INT NOT NULL,
 BANHO_AGENDA_COD_AGENDA INT NOT NULL,
 FORNECEDOR_COD_FORNECEDOR INT NOT NULL,
primary key (COD_PRODUTO),
foreign key (FORNECEDOR_COD_FORNECEDOR) references FORNECEDOR(COD_FORNECEDOR)
);

CREATE TABLE BANHO(
COD_BANHO INT NOT NULL auto_increment,
PROCEDIMENTO_BANHO VARCHAR(240) NOT NULL,
OBSERVACAO VARCHAR (240) NOT NULL,
AGENDA_COD_AGENDA INT NOT NULL,
primary key (COD_BANHO),
FOREIGN KEY (AGENDA_COD_AGENDA) REFERENCES AGENDA(COD_AGENDA)
);

CREATE TABLE PASSEIO(
COD_PASSEIO INT NOT NULL auto_increment,
HORAIRIO_PASSEIO TIME NOT NULL,
HORARIO_CHEGADA TIME NOT NULL,
QUANTIDADE_ANIMAL INT  NOT NULL,
OBSERVACAO_PASSEIO VARCHAR(240) NOT NULL,
AGENDA_COD_AGENDA INT NOT NULL,
primary key (COD_PASSEIO),
FOREIGN KEY (AGENDA_COD_AGENDA) REFERENCES AGENDA(COD_AGENDA));

CREATE TABLE ESTADIA(
COD_ESTADIA INT NOT NULL auto_increment,
DATA_ENTRADA DATE NOT NULL,
DATA_SAIDA DATE NOT NULL,
OBSERVACAO_ESTADIA VARCHAR(240) NOT NULL,
AGENDA_COD_AGENDA INT NOT NULL,
primary key (COD_ESTADIA),
FOREIGN KEY (AGENDA_COD_AGENDA) REFERENCES AGENDA(COD_AGENDA));

CREATE TABLE ESTOQUE (
COD_ESTOQUE int not null auto_increment,
QUANTIDADE_SAIDA INT NOT NULL,
DATA_SAIDA DATE NOT NULL,
PRODUTO_COD_PRODUTO INT NOT NULL,
FORNECEDOR_COD_FORNECEDOR INT NOT NULL,
FUNCIONARIO_COD_FUNCIONARIO INT NOT NULL,
primary key (COD_ESTOQUE),
foreign key (PRODUTO_COD_PRODUTO) references PRODUTO(COD_PRODUTO),
foreign key (FORNECEDOR_COD_FORNECEDOR) references FORNECEDOR(COD_FORNECEDOR),
foreign key (FUNCIONARIO_COD_FUNCIONARIO) references FUNCIONARIO(COD_FUNCIONARIO));
